export const offers = [
  {
    id: "atlas-pro-solo",
    name: "Pack Solo - 12 mois",
    displayPrice: "49,99 EUR",
    schemaPrice: "49.99",
    oldPrice: "70 EUR",
    bonus: "+6 mois offerts",
    tagline: "1 code (1 appareil simultane)",
    features: [
      "Codes officiels et certifies",
      "Garantie de remplacement en cas de souci",
      "Livraison automatique instantanee",
      "Compatible avec toutes les applications IPTV",
      "Replay et EPG inclus",
      "Paiement 100 % securise",
      "Support WhatsApp verifie 24/7",
    ],
  },
  {
    id: "atlas-pro-duo",
    name: "Pack Duo - 12 mois",
    displayPrice: "59,99 EUR",
    schemaPrice: "59.99",
    oldPrice: "90 EUR",
    bonus: "Offre limitee",
    tagline: "2 codes (2 appareils simultanes)",
    features: [
      "Codes officiels et certifies",
      "Garantie de remplacement en cas de souci",
      "Livraison automatique instantanee",
      "Compatible avec toutes les applications IPTV",
      "Replay et EPG inclus",
      "Paiement 100 % securise",
      "Support WhatsApp verifie 24/7",
    ],
  },
  {
    id: "atlas-pro-famille",
    name: "Pack Famille - 12 mois",
    displayPrice: "68,99 EUR",
    schemaPrice: "68.99",
    oldPrice: "120 EUR",
    bonus: "Offre limitee",
    tagline: "3 codes (3 appareils simultanes)",
    features: [
      "Codes officiels et certifies",
      "Garantie de remplacement en cas de souci",
      "Livraison automatique instantanee",
      "Compatible avec toutes les applications IPTV",
      "Replay et EPG inclus",
      "Paiement 100 % securise",
      "Support WhatsApp verifie 24/7",
    ],
  },
];

